server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1344

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
  jmx:
    enabled: true
  jmx.server:
    port: 8080
